# Generated by Django 4.1.1 on 2022-11-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
